# Generated by Django 5.0.6 on 2024-05-28 10:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('neighbourhood', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('verbose', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(null=True)),
                ('year_met', models.SmallIntegerField()),
                ('is_business', models.BooleanField(default=False)),
                ('profession', models.CharField(blank=True, max_length=50)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('dod', models.DateField(null=True)),
                ('middle_names', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField()),
                ('addresses', models.ManyToManyField(to='address_book.address')),
                ('family_members', models.ManyToManyField(to='address_book.contact')),
                ('met_through_contact', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address_book.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nationality', models.ManyToManyField(to='address_book.nation')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_book.contact')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address_book.nation'),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
                ('number', models.PositiveIntegerField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_book.contact')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='landline',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address_book.phonenumber'),
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=50)),
                ('transmission', models.CharField(choices=[('They receive to this address', 'They receive to this address'), ('You receive from this address', 'You receive from this address')], max_length=30)),
                ('address', models.CharField(max_length=96)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_book.contact')),
            ],
        ),
    ]
