# Generated by Django 5.0.6 on 2024-06-28 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='nation',
            options={'ordering': ['verbose']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='year_met',
            field=models.SmallIntegerField(choices=[(None, '-- Select Year --'), (2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011'), (2010, '2010'), (2009, '2009'), (2008, '2008'), (2007, '2007'), (2006, '2006'), (2005, '2005'), (2004, '2004'), (2003, '2003'), (2002, '2002'), (2001, '2001'), (2000, '2000'), (1999, '1999'), (1998, '1998'), (1997, '1997'), (1996, '1996')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='transmission',
            field=models.CharField(choices=[(None, '-- Select Transmission --'), ('they_receive', 'They receive to this address'), ('you_receive', 'You receive from this address')], max_length=12),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_book.cryptonetwork'),
        ),
    ]
