# Generated by Django 5.0.6 on 2024-07-25 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_auto_20240711_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='landline',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address_book.address'),
        ),
    ]
