# Generated by Django 5.0.6 on 2024-07-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_alter_contactaddress_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactaddress',
            options={'ordering': ['archived']},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['archived']},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ['archived']},
        ),
        migrations.AlterModelOptions(
            name='walletaddress',
            options={'ordering': ['archived']},
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='type',
            field=models.CharField(choices=[(None, '-- Select Type --'), ('HOME', 'Home'), ('WORK', 'Work'), ('CELL', 'Mobile'), ('FAX', 'Fax'), ('PAGER', 'Pager'), ('VOICE', 'Voice'), ('VIDEO', 'Video'), ('TEXT', 'Text')], default='CELL', max_length=12),
            preserve_default=False,
        ),
    ]
