# Generated by Django 5.0.6 on 2024-07-26 09:47

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_auto_20240725_1322'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='address',
            managers=[
                ('preferred', django.db.models.manager.Manager()),
            ],
        ),
    ]
