# Generated by Django 5.0.6 on 2024-08-23 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_auto_20240801_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address_book.profession'),
        ),
    ]
