# Generated by Django 4.2.13 on 2024-06-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_address_user_alter_contact_addresses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='met_through_contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='mutual_contacts',
            field=models.ManyToManyField(blank=True, to='address_book.contact'),
        ),
    ]
