# Generated by Django 5.0.6 on 2024-07-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0003_alter_contactaddress_options_alter_email_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[(None, '-- Select Type --'), ('HOME', 'Home'), ('WORK', 'Work'), ('PREF', 'Preferred')], default='HOME', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='type',
            field=models.CharField(choices=[(None, '-- Select Type --'), ('HOME', 'Home'), ('WORK', 'Work'), ('CELL', 'Mobile'), ('FAX', 'Fax'), ('PAGER', 'Pager'), ('VOICE', 'Voice'), ('VIDEO', 'Video'), ('TEXT', 'Text')], max_length=5),
        ),
    ]
