# Generated by Django 5.0.6 on 2024-07-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0004_email_type_alter_phonenumber_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[(None, '-- Select Type --'), ('HOME', 'Home'), ('WORK', 'Work'), ('DOM', 'Domestic'), ('INTL', 'International'), ('POSTAL', 'Postal'), ('PARCEL', 'Parcel'), ('PREF', 'Preferred')], default='HOME', max_length=6),
            preserve_default=False,
        ),
    ]
