# Generated by Django 5.0.6 on 2024-06-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0005_address_city_alter_address_address_line_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['country__verbose', 'city', 'address_line_1']},
        ),
    ]
