# Generated by Django 5.0.6 on 2024-07-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0006_alter_address_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='anniversary',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[(None, '-- Select Gender --'), ('m', 'Male'), ('f', 'Female')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
