# Generated by Django 5.0.6 on 2024-06-26 09:10

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0006_alter_phonenumber_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
