name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping --silent"

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set environment variables
      run: echo "DEBUG=True" >> $GITHUB_ENV

    - name: Check Python version
      run: python --version

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install pipenv
      run: pip install pipenv

    - name: Install Dependencies
      run: pipenv install

    - name: Wait for MySQL to start
      run: |
        while ! mysqladmin ping -h"127.0.0.1" --port=3306 --silent; do
          echo "Waiting for MySQL to start..."
          sleep 5
        done

    - name: Run Tests
      env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_PORT: 3306
        MYSQL_DB_NAME: ${{ secrets.DB_NAME }}
        MYSQL_USER: ${{ secrets.DB_USER }}
        MYSQL_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        pipenv run coverage run manage.py test
        pipenv run coverage report
        pipenv run coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov